version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nested-app-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14fl2dut57evr"
s3_prefix = "nested-app-example"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Env=\"satoshi\" Domain=\"smidorikawa.com\""
