ApiDomain:
  Type: AWS::ApiGateway::DomainName
  Properties:
    DomainName: !Ref EnvConfigDOMAINAsString
    EndpointConfiguration:
      Types:
        - REGIONAL
    RegionalCertificateArn: !Ref ApiCertificate

ApiUsersPathMapping:
  Type: AWS::ApiGateway::BasePathMapping
  Properties:
    BasePath: users
    DomainName: !Ref ApiDomain
    RestApiId:
      Fn::ImportValue: !Sub Users-${EnvironmentTagName}-RestApiId
    Stage:
      Fn::ImportValue: !Sub Users-${EnvironmentTagName}-StageName
ApiAccountsPathMapping:
  Type: AWS::ApiGateway::BasePathMapping
  Properties:
    BasePath: accounts
    DomainName: !Ref ApiDomain
    RestApiId:
      Fn::ImportValue: !Sub Accounts-${EnvironmentTagName}-RestApiId
    Stage:
      Fn::ImportValue: !Sub Accounts-${EnvironmentTagName}-StageName
