AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    
Parameters:
  ENV:
    Type: String
    default: dev

Resources:
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "", [ "sample-bucket", "-", !Ref Env ] ]
  SampleRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      Domain:
        BasePath:
          - /api
  SampleMyLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location: common-layer-sample/template.yaml
  SampleMyLambdas:
    Type: AWS::Serverless::Application
    Properties:
      Location: sam-lambda-sample/template.yaml
      Parameters:
        ApiId: !Ref SampleRestApi
        SamplebucketArn: !Ref SampleBucket

Outputs:
  SampleMyLayer:
    Description: "Sample Layer ARN"
    Value: !Ref SampleMyLayer
  SampleMyLambdas:
    Description: "Sample My Lambdas ARN"
    Value: !Ref SampleMyLambdas
