AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5

Parameters:
  ENV:
    Type: String
    Default: satoshi

Resources:
  SampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ "", [ "sample-bucket", "-", "satoshi"] ]
  SampleMyLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location: common-layer-sample/template.yaml
      Parameters:
        ENV: !Ref ENV
  SampleMyLambdas:
    Type: AWS::Serverless::Application
    DependsOn:
      - SampleMyLayer
      - SampleBucket
    Properties:
      Location: sam-lambda-sample/template.yaml
      Parameters:
        ENV: !Ref ENV
        SamplebucketName: !Ref SampleBucket
        SamplebucketArn: !GetAtt SampleBucket.Arn
  SampleMyAnotherLambdas:
    Type: AWS::Serverless::Application
    DependsOn:
      - SampleMyLayer
      - SampleBucket
    Properties:
      Location: sam-lambda-another-layer/template.yaml
      Parameters:
        ENV: !Ref ENV
        SamplebucketName: !Ref SampleBucket
        SamplebucketArn: !GetAtt SampleBucket.Arn

Outputs:
  SampleMyLayer:
    Description: "Sample Layer ARN"
    Value: !Ref SampleMyLayer
  SampleMyLambdas:
    Description: "Sample My Lambdas ARN"
    Value: !Ref SampleMyLambdas
