AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-lambda-sample

Globals:
  Function:
    Timeout: 30

Parameters:
  ENV:
    Type: String
  Layer:
    Type: String
    Default: ''
  SamplebucketName:
    Type: String
  SamplebucketArn:
    Type: String
  SampleRoleArn:
    Type: String

Resources:
  SampleRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
  SampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !Ref SampleRoleArn
      Layers:
        - !Ref Layer
      Environment:
        Variables:
          SamplebucketName: !Ref SamplebucketName
          BucketArn: !Ref SamplebucketArn
      Events:
        SampleLambdaApi:
          Type: Api
          Properties:
            Path: /hello-world
            Method: get
            RestApiId: !Ref SampleRestApi

Outputs:
  SampleLambdaFunction:
    Description: "Sample Lambda Function ARN"
    Value: !GetAtt SampleLambdaFunction.Arn
