AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-lambda-sample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  ENV:
    Type: String
  Layer:
    Type: String
    Default: ''
    # Default: arn:aws:lambda:us-east-1:108346452320:layer:sample-my-layer:1
  SamplebucketName:
    Type: String
  SamplebucketArn:
    Type: String
  # ApiId:
  #   Type: String

Resources:
  SampleLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: "*"
      # Layers:
      #   - !Ref Layer
      Environment:
        Variables:
          SamplebucketName: !Ref SamplebucketName
          BucketArn: !Ref SamplebucketArn
      # Events:
      #   SampleLambdaApi:
      #     Type: Api
      #     Properties:
      #       Path: /sample
      #       Method: get
      #       RestApiId: !Ref ApiId

Outputs:
  SampleLambdaFunction:
    Description: "Sample Lambda Function ARN"
    Value: !GetAtt SampleLambdaFunction.Arn
