AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-lambda-sample

Transform:
- AWS::Serverless-2016-10-31

Parameters:
  Env:
    Type: String
  SampleRoleArn:
    Type: String

Resources:
  SimpleQueue:
    Type: AWS::SQS::Queue

  SQSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that logs the payload of messages sent to an associated SQS queue.
      Role: !Ref SampleRoleArn
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Handler: src/handlers/sqs-payload-logger.sqsPayloadLoggerHandler
      # This property associates this Lambda function with the SQS queue defined above, so that whenever the queue
      # receives a message, the Lambda function is invoked
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt SimpleQueue.Arn
      MemorySize: 128
      Timeout: 25 # Chosen to be less than the default SQS Visibility Timeout of 30 seconds
