AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-lambda-sample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  ENV:
    Type: String
  ApiId:
    Type: String
  Layer:
    Type: String
    Default: !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:sample-my-layer:1'
              # arn:aws:lambda:us-east-1:108346452320:layer:sample-my-layer:1
  SamplebucketArn:
    Type: String

Resources:
  SampleLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Layers:
        - !Ref Layer
      Environment:
        Variables:
          Bucket: !Ref SamplebucketArn
      Events:
        SampleLambdaApi:
          Type: Api
          Properties:
            Path: /sample
            Method: get
            RestApiId: !Ref ApiId

Outputs:
  SampleLambdaFunction:
    Description: "Sample Lambda Function ARN"
    Value: !GetAtt SampleLambdaFunction.Arn
