AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for sam-lambda-sample

Globals:
  Function:
    Timeout: 30

Parameters:
  Env:
    Type: String
  SampleRoleArn:
    Type: String

Resources:
  SampleLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: !Ref SampleRoleArn
      FunctionName: !Sub ${Env}-sample-lambda
      # Layers:
      #   - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:sample-my-layer:1'

Outputs:
  SampleLambdaFunction:
    Description: "Sample Lambda Function ARN"
    Value: !GetAtt SampleLambdaFunction.Arn
  SampleLambdaFunctionName:
    Description: "Sample Lambda Function ARN"
    Value: !Sub ${Env}-sample-lambda
