AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for common-layer-sample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  Env:
    Type: String

Resources:
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub ${Env}-my-layer
      ContentUri: my_layer/
      CompatibleRuntimes:
        - python3.7
      RetentionPolicy: Retain
  PortalCoreLayerPermissionKxDev:
    Type: AWS::Lambda::LayerVersionPermission
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties: 
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref MyLayer
      Principal: !Sub 'arn:aws:iam::${AWS::AccountId}:root'

Outputs:
  MyLayer:
    Description: Sample My Layer ARN"
    Value: !Ref MyLayer
  MyLayerName:
    Description: Sample My Layer Name"
    Value: !Sub ${Env}-my-layer
