AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9

  Sample SAM Template for common-layer-sample

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: MyLayer
      ContentUri: my_layer/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Retain

Outputs:
  MyLayer:
    Description: Sample My Layer ARN"
    Value: !Ref MyLayer
